### ISSUE TITLE
version without ndk, headers-more and lua

### ISSUE THREAD

**Issue by brunoqc** [Meroje/alpine-nchan#2]
It could be nice if the main image only has nchan and there would be a tagged version with ndk, headers-more and lua.

**Comment by Meroje** [comment]
Yes, that's not a bad idea

**Comment by Meroje** [comment]
I just pushed the "standard" tag that is simply the nginx official Dockerfile with nchan added. Please let me know if that helps

**Comment by brunoqc** [comment]
Thanks.
