### ISSUE TITLE
How do you configure nginx?

### ISSUE THREAD

**Issue by brunoqc** [Meroje/alpine-nchan#3]
I see volumes for `/etc/nginx/sites-enabled` and `/etc/nginx/conf.d` but I don't see any includes in the default nginx.conf and there's no volume for `/etc/nginx/conf`.

**Comment by Meroje** [comment]
Those are leftovers from the Dockerfile I took inspiration from (I may rewrite to base upon the [official](https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile)). Configs should be baked in own image by extending, they don't need to be in a volume anyway.

**Comment by brunoqc** [comment]
Thanks.
